NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [4]:
import numpy as np

List vs Numpy - Time Taken

In [7]:
from time import process_time

In [14]:
myList = [i for i in range(10000)]

start_time = process_time()

myList = [i+5 for i in myList]

end_time = process_time()
print(end_time - start_time)

0.0003382499999995403


In [19]:
myNpArray = np.array([i for i in range(10000)])

start_time_np = process_time()

myNpArray = +5
end_time_np = process_time()

print(end_time_np - start_time_np)

4.5148000001660193e-05


Create numpy Array

In [20]:
np_array = np.array([1,2,3,4,5,6,7])

In [21]:
print(np_array)

[1 2 3 4 5 6 7]


In [22]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# array of a particular value
# row,column 
z = np.full((5,1),5)
print(z)

[[5]
 [5]
 [5]
 [5]
 [5]]


In [31]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.12461527 0.11158452 0.36381388 0.46444609]
 [0.21061712 0.02749622 0.82967278 0.32083037]
 [0.98502833 0.93558421 0.32758617 0.22931007]]


In [33]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[73 46 40 71 77]
 [94 22 29 72 26]
 [59 36 35 30 90]]


In [46]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [48]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,2)
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [50]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
type(list2)

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [51]:
c = np.random.randint(10,90,(5,5))
print(c)

[[30 58 83 58 13]
 [55 66 87 19 69]
 [35 67 40 26 79]
 [65 46 61 24 25]
 [79 74 16 15 22]]


In [52]:
# array dimension
print(c.shape)

(5, 5)


In [53]:
# number of dimensions
print(c.ndim)

2


In [54]:
# number of elements in an array
print(c.size)

25


In [55]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [56]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [57]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [58]:
print(a)
print(b)

[[8 8 8]
 [6 1 3]
 [0 9 9]]
[[11 19 17]
 [16 14 10]
 [18 16 12]]


In [59]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 27 25]
 [22 15 13]
 [18 25 21]]
[[ -3 -11  -9]
 [-10 -13  -7]
 [-18  -7  -3]]
[[ 88 152 136]
 [ 96  14  30]
 [  0 144 108]]
[[0.72727273 0.42105263 0.47058824]
 [0.375      0.07142857 0.3       ]
 [0.         0.5625     0.75      ]]


In [60]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [61]:
print(a)
print(b)

[[1 1 4]
 [9 5 8]
 [5 7 1]]
[[17 12 12]
 [19 18 15]
 [16 16 18]]


In [62]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 13 16]
 [28 23 23]
 [21 23 19]]
[[-16 -11  -8]
 [-10 -13  -7]
 [-11  -9 -17]]
[[ 17  12  48]
 [171  90 120]
 [ 80 112  18]]
[[0.05882353 0.08333333 0.33333333]
 [0.47368421 0.27777778 0.53333333]
 [0.3125     0.4375     0.05555556]]


Array Manipulation

In [63]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 2 3]
 [0 0 6]]
(2, 3)


In [64]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 0]
 [2 0]
 [3 6]]
(3, 2)


In [65]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 7 2]
 [3 0 3]]
(2, 3)


In [66]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 3]
 [7 0]
 [2 3]]
(3, 2)


In [67]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 5 1]
 [7 1 3]]
(2, 3)


In [68]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 5]
 [1 7]
 [1 3]]
(3, 2)
