NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

In [3]:
myList = [i for i in range(10000)]

start_time = process_time()

myList = [i+5 for i in myList]

end_time = process_time()
print(end_time - start_time)

0.013764264000000193


In [4]:
myNpArray = np.array([i for i in range(10000)])

start_time_np = process_time()

myNpArray = +5
end_time_np = process_time()

print(end_time_np - start_time_np)

9.762000000002047e-05


Create numpy Array

In [5]:
np_array = np.array([1,2,3,4,5,6,7])

In [6]:
print(np_array)

[1 2 3 4 5 6 7]


In [7]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# array of a particular value
# row,column 
z = np.full((5,1),5)
print(z)

[[5]
 [5]
 [5]
 [5]
 [5]]


In [10]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.01702407 0.48804193 0.17286394 0.44765931]
 [0.12001825 0.37758951 0.52988803 0.13172107]
 [0.45056787 0.76929166 0.56035374 0.08750705]]


In [12]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[89 45 17 95 63]
 [90 53 52 79 94]
 [57 99 46 94 98]]


In [13]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [14]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,2)
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [15]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
type(list2)

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [16]:
c = np.random.randint(10,90,(5,5))
print(c)

[[62 70 30 40 35]
 [66 70 10 20 87]
 [15 63 58 88 52]
 [18 13 72 81 49]
 [20 45 24 82 29]]


In [17]:
# array dimension
print(c.shape)

(5, 5)


In [18]:
# number of dimensions
print(c.ndim)

2


In [19]:
# number of elements in an array
print(c.size)

25


In [20]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [21]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [23]:
print(a)
print(b)

[[3 1 9]
 [3 4 8]
 [9 2 7]]
[[19 14 15]
 [16 11 12]
 [16 14 11]]


In [24]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 15 24]
 [19 15 20]
 [25 16 18]]
[[-16 -13  -6]
 [-13  -7  -4]
 [ -7 -12  -4]]
[[ 57  14 135]
 [ 48  44  96]
 [144  28  77]]
[[0.15789474 0.07142857 0.6       ]
 [0.1875     0.36363636 0.66666667]
 [0.5625     0.14285714 0.63636364]]


In [25]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [26]:
print(a)
print(b)

[[6 0 0]
 [8 6 3]
 [3 4 6]]
[[13 12 19]
 [17 14 12]
 [11 18 12]]


In [27]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 12 19]
 [25 20 15]
 [14 22 18]]
[[ -7 -12 -19]
 [ -9  -8  -9]
 [ -8 -14  -6]]
[[ 78   0   0]
 [136  84  36]
 [ 33  72  72]]
[[0.46153846 0.         0.        ]
 [0.47058824 0.42857143 0.25      ]
 [0.27272727 0.22222222 0.5       ]]


Array Manipulation

In [28]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 3 9]
 [7 2 2]]
(2, 3)


In [29]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 7]
 [3 2]
 [9 2]]
(3, 2)


In [30]:
array = np.random.randint(0,10,(2,3))
print(array)

[[0 7 9]
 [2 3 0]]


In [31]:
trans2 = array.T
print(trans2)
print(trans2.shape)
print(array.shape)

[[0 2]
 [7 3]
 [9 0]]
(3, 2)
(2, 3)


In [32]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 0 1]
 [6 9 9]]
(2, 3)


In [33]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 0]
 [1 6]
 [9 9]]
(3, 2)
